version: "3"

services:
  db_server:
    image: "redis:latest"
    ports:
      - "6379:6379"
      # - "20000-22000:20000-22000"
    hostname: "redis"
    networks:
      - redis
    command: ["redis-server", "--appendonly", "yes"]
  scc-state-01:
    build: ./scc-state
    ports:
      - "7777:7777"
    hostname: state
    networks:
      - state
      - server
      - broker
    depends_on:
      - db_server
    command: "npm start"
  scc-broker-01:
    build: ./scc-broker
    # ports:
    # - "8888:8888"
    # - "19000-24000:19000-24000"
    hostname: broker
    networks:
      - state
      - server
    depends_on:
      - scc-state-01
    command: "npm start"
  express_server:
    build: ./
    ports:
      - 19093:19093
      # - "19000-24000:19000-24000"
    volumes:
      - ./backend/:/backend
    networks:
      - redis
    depends_on:
      - db_server
    command: "npm start"
  test-server-01:
    build: ./test-server
    # ports:
    # - "19000-24000"
    # - "8000:8000"
    # - "19000-24000:19000-24000"
    hostname: server
    networks:
      - redis
      - state
      - broker
    restart: on-failure
    depends_on:
      - scc-broker-01
    command: "npm start"

networks:
  redis:
    driver: bridge
  state:
    driver: bridge
  server:
    driver: bridge
  broker:
    driver: bridge
